name: Deploy Web on Production

on:
  push:
    branches:
      - production

jobs:
  build-and-deploy-web:
    runs-on: ubuntu-latest
    env:
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }} # yamllint disable-line
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Instalar dependencias
        working-directory: ./mcm-app
        run: npm ci

      - name: Instalar EAS CLI
        run: npm install -g eas-cli@latest

      - name: Verificar autenticación Expo
        run: eas whoami

      - name: Build web assets
        working-directory: ./mcm-app
        run: npx expo export --platform web

      - name: Deploy to Expo Hosting
        working-directory: ./mcm-app
        run: npx eas deploy --platform web --prod --non-interactive
